EShopping/Models/ViewModels/Shop/CategoryVM.cs
using EShopping.Models.Data;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace EShopping.Models.ViewModels.Shop
{
    public class CategoryVM
    {
        public CategoryVM()
        {

        }
        public CategoryVM(CategoryDTO row)
        {
            Id = row.Id;
            Name = row.Name;
            Slug = row.Slug;
            Sorting = row.Sorting;
        }

        public int Id { get; set; }
        public string Name { get; set; }
        public string Slug { get; set; }
        public int Sorting { get; set; }
    }
}

EShopping/Models/ViewModels/Shop/ProductVM.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using EShopping.Models.Data;
using System.Web.Mvc;
using System.ComponentModel.DataAnnotations;

namespace EShopping.Models.ViewModels
{
    public class ProductVM
    {

        public ProductVM()
        {

        }
        public ProductVM(ProductDTO row)
        {
            Id = row.Id;
            Name = row.Name;
            Slug = row.Slug;
            Description = row.Description;
            Price = row.Price;
            CategoryId = row.CategoryId;
            CategoryName = row.CategoryName;
            ImageName = row.ImageName;
        }



        public int Id { get; set; }
        [Required]
        public string Name { get; set; }
        public string Slug { get; set; }
        [Required]
        public string Description { get; set; }
        public decimal Price { get; set; }
        [Required]
        public int CategoryId { get; set; }
        public string CategoryName { get; set; }
        public string ImageName { get; set; }

        public IEnumerable<SelectListItem>Categories { get; set; }
        public IEnumerable<string>GalleryImages { get; set; }

    }
}

EShopping/Areas/Admin/Controllers/ShopController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using EShopping.Models.ViewModels.Shop;
using EShopping.Models.Data;
using EShopping.Models.ViewModels;
using System.IO;
using System.Web.Helpers;
using PagedList;

namespace EShopping.Areas.Admin.Controllers
{
    public class ShopController : Controller
    {
        // GET: Admin/Shop/Categories
        public ActionResult Categories()
        {
            List<CategoryVM> CategoryVMList;
            using (EShoppingDb db = new EShoppingDb())
            {
                //init list
                CategoryVMList = db.Categories.ToArray().OrderBy(x => x.Sorting).Select(x => new CategoryVM(x)).ToList();
            }
            return View(CategoryVMList);
        }


        //post: admin/shop/AddNewCategory
        [HttpPost]
        public string AddNewCategory(string catName)
        {
            string id;
            using (EShoppingDb db = new EShoppingDb())
            {
                if (db.Categories.Any(c => c.Name == catName))
                    return "titletaken";

                CategoryDTO dto=new CategoryDTO();
                dto.Name = catName;
                dto.Slug = catName.Replace(" ", "-").ToLower();
                dto.Sorting = 100;
                db.Categories.Add(dto);
                db.SaveChanges();

                id = dto.Id.ToString();

            }
                return id;
        }


        [HttpPost]
        public void ReorderCategories(int[] id)
        {
            using (EShoppingDb db = new EShoppingDb())
            {
                int count = 1;
                CategoryDTO dto;
                foreach (var catId in id)
                {
                    dto = db.Categories.Find(catId);
                    dto.Sorting = count;

                    db.SaveChanges();
                    count++;
                }
            }
        }


        public ActionResult DeleteCategory(int id)
        {
            using (EShoppingDb db = new EShoppingDb())
            {

                CategoryDTO dto = db.Categories.Find(id);
                db.Categories.Remove(dto);

                db.SaveChanges();

            }
            return RedirectToAction("Categories");
        }

        [HttpPost]
        public string RenameCategory(string newCatName, int id)
        {
            using (EShoppingDb db = new EShoppingDb())
            {
                if (db.Categories.Any(c => c.Name == newCatName))
                    return "titletaken";
                CategoryDTO dto = db.Categories.Find(id);
                dto.Name = newCatName;
                dto.Slug = newCatName.Replace(" ", "-").ToLower();
                db.SaveChanges();
            }
            return "ok";
        }


        [HttpGet]
        public ActionResult AddProduct()
        {
            ProductVM model = new ProductVM();
            using (EShoppingDb db = new EShoppingDb())
            {
                model.Categories = new SelectList(db.Categories.ToList(), "Id", "Name");
            }
                return View(model);
        }

        [HttpPost]
        public ActionResult AddProduct(ProductVM model, HttpPostedFileBase file)
        {
            //check model state
            if (!ModelState.IsValid)
            {
                using (EShoppingDb db = new EShoppingDb())
                {
                    model.Categories = new SelectList(db.Categories.ToList(), "id", "Name");
                    return View(model);
                }

            }


            // check if the produc name is unique
            using (EShoppingDb db = new EShoppingDb())
            {
                if (db.Products.Any(p => p.Name == model.Name))
                {
                    model.Categories = new SelectList(db.Categories.ToList(), "id", "Name");
                    ModelState.AddModelError("", "the product name is taken !");
                    return View(model);
                }
            }


            //declare prod id 
            int id;
            using (EShoppingDb db = new EShoppingDb())
            {
                ProductDTO prod = new ProductDTO();
                prod.Name = model.Name;
                prod.Slug = model.Name.Replace(" ", "-").ToLower();
                prod.Description = model.Description;
                prod.Price = model.Price;
                prod.CategoryId = model.CategoryId;

                CategoryDTO cat = db.Categories.Find(Convert.ToInt32(prod.CategoryId));
                prod.CategoryName = cat.Name;

                db.Products.Add(prod);
                db.SaveChanges();

                //get id after put in DB
                id = prod.Id;

            }
            TempData["Success_message"] = "Product added successfully !";
             
            var originalDirectory = new DirectoryInfo(string.Format("{0}Images\\Uploads", Server.MapPath(@"\")));

            var pathString1 = Path.Combine(originalDirectory.ToString(), "Products");
            var pathString2 = Path.Combine(originalDirectory.ToString(), "Products\\"+id.ToString());
            var pathString3 = Path.Combine(originalDirectory.ToString(), "Products\\" + id.ToString() +"\\Thumbs");
            var pathString4 = Path.Combine(originalDirectory.ToString(), "Products\\" + id.ToString() + "\\Gallery");
            var pathString5 = Path.Combine(originalDirectory.ToString(), "Products\\" + id.ToString() + "\\Gallery\\Thumbs");

            if (!Directory.Exists(pathString1))
                Directory.CreateDirectory(pathString1);

            if (!Directory.Exists(pathString2))
                Directory.CreateDirectory(pathString2);

            if (!Directory.Exists(pathString3))
                Directory.CreateDirectory(pathString3);

            if (!Directory.Exists(pathString4))
                Directory.CreateDirectory(pathString4);

            if (!Directory.Exists(pathString5))
                Directory.CreateDirectory(pathString5);

            //check the file is uploaded 
            if (file != null && file.ContentLength > 0)
            {
                string extension = file.ContentType.ToLower();
                if (extension != "image/jpg"
                   && extension != "image/jpeg"
                   && extension != "image/pjpeg"
                   && extension != "image/gif"
                   && extension != "image/x-png"
                   && extension != "image/png")
                {
                    using (EShoppingDb db = new EShoppingDb())
                    {
                        model.Categories = new SelectList(db.Categories.ToList(), "id", "Name");
                        ModelState.AddModelError("", "Image was not uploaded or wrong image formate !");
                        return View(model);

                    }


                }
                string imageName = file.FileName;

                using (EShoppingDb db = new EShoppingDb())
                {
                    ProductDTO dto = db.Products.Find(id);
                    dto.ImageName = imageName;
                    db.SaveChanges();
                }
                //set original and thumb image paths
                var path = string.Format("{0}\\{1}", pathString2, imageName);
                var path1 = string.Format("{0}\\{1}", pathString3, imageName);

                //save original
                file.SaveAs(path);

                //create and save thumb
                WebImage img = new WebImage(file.InputStream);
                img.Resize(200, 200);
                img.Save(path1);
             


            }

            return RedirectToAction("AddProduct");
        }

        [HttpGet]
        public ActionResult Products(int? page, int? catId)
        {
            List<ProductVM> listOfProductVM;

            var pageNumber = page ?? 1; // if page =null put one .

            using (EShoppingDb db = new EShoppingDb())
            {
                listOfProductVM = db.Products.ToArray()
                    .Where(p => catId == null || catId == 0 || p.CategoryId == catId)
                    .Select(p => new ProductVM(p))
                    .ToList();

                ViewBag.Categories = new SelectList(db.Categories.ToList(), "Id", "Name");
                ViewBag.SelecteCat = catId.ToString();
                var onePageOfProducts = listOfProductVM.ToPagedList(pageNumber,3);

                ViewBag.onePageOfProducts = onePageOfProducts;
            }


                return View(listOfProductVM);
        }



    }
}

EShopping/Areas/Admin/Views/Shop/AddProduct.cshtml
@model EShopping.Models.ViewModels.ProductVM

@{
    ViewBag.Title = "Add Product";
}

<h2>Add Product</h2>


@if (TempData["Success_message"] != null)
{
    <div class="alert alert-success">
        @TempData["Success_message"]
    </div>
}

@using (Html.BeginForm("AddProduct","Shop",FormMethod.Post,new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()
     
    <div class="form-horizontal">
      
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        

        <div class="form-group">
            @Html.LabelFor(model => model.Description, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.TextAreaFor(model => model.Description, new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Price, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Price, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Price, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <label class = "control-label col-md-2" for="HasSidebar">Category</label>
            <div class="col-md-10">
                @Html.DropDownListFor(model =>model.CategoryId,Model.Categories,"select a Category ", new { @class = "form-control"  })
                @Html.ValidationMessageFor(model => model.CategoryName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <label class="control-label col-md-2" for="HasSidebar">Product Image</label>
            <div class="col-md-10">
               <input type="file" name="file" id="ImageUpload" />
                <img src="#" id="imgpreview" />

            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Add Product" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to Products", "Products")
</div>


@section scripts
{
    <script src="https://code.jquery.com/ui/1.12.0/jquery-ui.min.js"></script>



<script>
    $(function () {
////////////////////////////preview selected image////////////////////

        function readURL(input) {
            if (input.files && input.files[0])
            {
                var reader = new FileReader();
                reader.onload = function (e) {
                    $("img#imgpreview")
                    .attr("src", e.target.result)
                    .width(200)
                    .height(200);

                }
                reader.readAsDataURL(input.files[0]);
            }

        }
        
        $("#ImageUpload").change(function () {
            readURL(this);
        });
 



    });

</script>

}

EShopping/Areas/Admin/Views/Shop/Categories.cshtml
@model IEnumerable<EShopping.Models.ViewModels.Shop.CategoryVM>

@{
    ViewBag.Title = "Categories";
}

<h2>Categories</h2>
<div class="new-cat">
<input type="text" id="newcatname"/>

    <p>
        <a href="#" id="newcata">Add new category</a>
        <span id="ajax-text"></span>
<img src="~/Content/img/ajax-loader.gif"/></sapn>
    </p>
</div>

@if (!Model.Any())
{
    <h1 class="text-center">there is on categories  </h1>
}
else
{
<table class="table sorting categories" id="pages">
    <tr class="home">
        <th>
            @Html.DisplayNameFor(model => model.Name)
        </th>
        
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr id="id_@item.Id">
        <td>
            <div class="ajaxdivtd"></div>
            @Html.EditorFor(modelItem => item.Name, new { htmlAttributes = new { @class = "form-control",@readonly="readonly" } })
            
        </td>
       
        <td>
      
            @Html.ActionLink("Delete", "DeleteCategory", new { id=item.Id },new { @class="delete"})
        </td>
    </tr>
}

</table>

}


@section scripts
{
    <script src="https://code.jquery.com/ui/1.12.0/jquery-ui.min.js"></script>



    <script>
    $(function () {


        //Add new category ////////////////////////////////////////
        var newCatA = $("a#newcata");
        var newCatInputText = $("#newcatname");
        var ajaxText = $("#ajax-text");
        var table = $("table#pages tbody");

        newCatInputText.keyup(function (e) {

            if (e.keyCode == 13)
                newCatA.click();
        });


        newCatA.click(function (e) {
            e.preventDefault();
            var catName = newCatInputText.val();

            if (catName.length < 2) {
                alert("category name must be at least 2 characters !");
                return false
            }
            ajaxText.show();
            url = "/Admin/Shop/AddNewCategory";
            $.post(url, { catName: catName }, function (data) {
                var response = data.trim();
                if (response == "titletaken")
                {
                    ajaxText.html("<span class='alert alert-danger'>this title is taken </span>");
                    setTimeout(function () {
                        ajaxText.fadeOut("fast", function () {
                            ajaxText.html("<img src='~/Content/img/ajax-loader.gif'/>")
                        });

                    }, 2000);
                    return false;
               
                }

                else {

                    if (!$("table#pages ").length) {
                        location.reload();
                    }
                    else
                    {
                        ajaxText.html("<span class='alert alert-success'>category has been added  </span>");
                        setTimeout(function () {
                            ajaxText.fadeOut("fast", function () {
                                ajaxText.html("<img src='~/Content/img/ajax-loader.gif'/>")
                            });

                        }, 2000);
                        
                        newCatInputText.val("");

                        var toAppend = $("table#pages tbody tr:last").clone();
                        toAppend.attr("id","id_"+data);
                        toAppend.find("#item_Name").val(catName);
                        toAppend.find("a.delete").attr("href", "/Admin/Shop/DeleteCategory/" + data);
                        table.append(toAppend);
                        table.sortable("refresh");


                    }

                }

            });


        });

        //delete confirm ////////////////////////////////////////

        $("table#pages tbody").sortable({
            items: "tr:not(.home)",
            placholder: "ui-state-highlight",
            update: function () {
                var ids = $("table#pages tbody").sortable("serialize");
                var url = "/Admin/Shop/ReorderCategories";

                $.post(url, ids, function (data) {

                });
            }


        });


        ///////////////////// reordering cat/////////////////////////////////

        $("a.delete").click(function () {
            if (!confirm("confirm Category deletion "))
                return false;

        });
        /////////////////////////////renaming category//////////////////////////
        var originalTextBaxValue;
        $("table#pages input.text-box").dblclick(function () {
            originalTextBaxValue = $(this).val();
            $(this).attr("readonly", false);

        });

        $("table#pages input.text-box").keyup(function (e) {
            if (e.keyCode == 13)
                $(this).blur();
        });

        $("table#pages input.text-box").blur(function () {
            var $this = $(this);
            var ajaxdivtd = $this.parent().find(".ajaxdivtd");
            var newCatName = $this.val();
            var id=  $this.parent().parent().attr("id").substring(3);
            var url = "/Admin/Shop/RenameCategory/";
            if (newCatName.length < 2) {
                alert("category name must be at least 2 characters !");
                $this.attr("readonly", true);
                return false
            }

            $.post(url, { newCatName: newCatName, id: id }, function (data) {
                var response = data.trim();
                if (response == "titletaken") {
                    $this.val(originalTextBaxValue);
                    ajaxdivtd.html("<span class='alert alert-danger'>this title is taken </span>").show();
                }
                else {
                    ajaxdivtd.html("<span class='alert alert-success'>category has been changed ! </span>").show();

                }

                setTimeout(function () {
                    ajaxdivtd.fadeOut("fast", function () { ajaxdivtd.html("") });
                }, 2000);
            }).done(function () { $this.attr("readonly",true)});



        });


    });

    </script>

}

EShopping/Areas/Admin/Views/Shop/Products.cshtml
@model IEnumerable<EShopping.Models.ViewModels.ProductVM>

@{
    ViewBag.Title = "Products";
}
@using PagedList.Mvc ;
@using PagedList;

<h2>Products</h2>

<select id="SelecteCategory" name="SelecteCategory" >
    <option value="0">All</option>
    @foreach (var item in ViewBag.Categories)
    {
        if (ViewBag.SelectedCat == item.Value)
        {
            <option value=@item.Value selected="selected">@item.Text</option>
        }
        else
        {
            <option value=@item.Value >@item.Text</option>
        }
    }

</select>
</br></br>
<p>
    @Html.ActionLink("Add New Product ", "AddProduct")
</p>
<table class="table">
    <tr>
        <th>
            Name
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Slug)
        </th>
        <th>
            Description
        </th>
        <th>
            Price
        </th>
        
        <th>
            Image Name
        </th>
        <th></th>
    </tr>

@foreach (var product in ViewBag.onePageOfProducts)
{
    <li>@product.Name</li>
    <tr>
        <td>@product.Name </td>
        <td>@product.Description </td>
        <td>@product.Price </td>
        <td>
            <a href="/Admin/Shop/EditProduct/@product.Id" />
            <img src="/Images/Uploads/Products/@product.Id/Thumbs/@product.ImageName">
        </td>


        <td>
            @Html.ActionLink("Edit", "EditProduct", new { id = @product.Id }) |
            @Html.ActionLink("Delete", "DeleteProduct", new { id = @product.Id })
        </td>

    </tr>

}


</table>
@Html.PagedListPager((IPagedList)ViewBag.onePageOfProducts, page => Url.Action("Products",new { page, catId = ViewBag.SelecteCat }));


@section scripts
{
    <script src="https://code.jquery.com/ui/1.12.0/jquery-ui.min.js"></script>



    <script>
    $(function () {



        ///////////////////////////////Selecte Category///////////////////////////////////////
        $("#SelecteCategory").on("change", function () {
            var url = $(this).val();
            if (url)
            {
                window.location = "/Admin/Shop/Products?catId=" + url;
            }

            return false;

        });
    //////////////////////////////////////////////////////////////////////
        $("a.delete").click(function () {
            if (!confirm("confirm page deletion "))
                return false;

        });
        ///////////////////////////////////////////////////////


    });

    </script>

}